title: "ELM GWANDARU"
description: Poems, writings and artwork by Elm Gwandaru, blending surrealism and African motifs.
seo_description: A surrealist journey through poems, writings, and artwork by Elm Gwandaru — blending raw imagination with African heritage and modern rebellion.

url: "https://leohybrid.github.io/elm-gwandaru"
baseurl: ""  # leave blank for GitHub Pages

theme: jekyll-theme-chirpy

timezone: Africa/Nairobi
lang: en

# Pagination
paginate: 10
paginate_path: "/page:num/"
permalink: pretty

# Include pages & posts
include:
  - _pages
  - _posts

# Plugins (must match Gemfile)
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-include-cache

# Exclude unnecessary folders/files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - feed.xml

# Disable built-in feed
feed:
  disable: true
