title: ELM GWANDARU
description: Poems, writing and artwork by Elm Gwandaru, blending surrealism and African motifs.
url: "https://leohybrid.github.io/elm-gwandaru"
timezone: Africa/Nairobi
permalink: pretty
include:
  - _pages
  - _posts
plugins:
  - jekyll-include-cache