source "https://rubygems.org"

gem "jekyll", "~> 4.3.4"
gem "jekyll-theme-chirpy", "~> 7.0"
gem "html-proofer"
gem "jekyll-include-cache"
gem "tzinfo", "~> 2.0"
gem "tzinfo-data", "~> 1.2025"
gem "csv", "~> 3.3"
gem "base64", "~> 0.2"