name: Pages
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pages:
    runs-on: ubuntu-latest
    concurrency:
      group: pages
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.9
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # cache: 'npm'   # 🔴 disabled npm cache to avoid rollup mismatch

      - name: Install dependencies
        run: |
          bundle install
          npm install   # 🔄 replaced npm ci with npm install

      - name: Build with Jekyll
        run: bundle exec jekyll b --profile

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site/'

  deploy:
    needs: pages
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
